# Generated by Django 4.0.2 on 2022-03-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('seo_title', models.CharField(max_length=59)),
                ('seo_description', models.CharField(max_length=160)),
                ('abstract', models.CharField(max_length=160)),
                ('body', models.TextField(default='')),
                ('duration', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=20)),
                ('start_date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('location', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
